version: "3"
services:
  db:
    image: mysql:5.6
    environment:
      MYSQL_ROOT_PASSWORD: 1
      MYSQL_DATABASE: sms-tracking
    ports:
      - 3306:3306
    volumes:
      - ./db:/var/lib/mysql/
